"""Streaming JSONL transcript harvester.

Reads ``~/.claude/projects/<encoded-cwd>/<session>.jsonl`` one line at a time —
single pass, O(1) memory, corrupt-line-tolerant — and emits cheap
``SessionDigest`` value objects (recurring-task intent + correction pairs).
``beartype`` guards the boundary so the typed contract holds even though the
input is untrusted JSON whose schema can drift.
"""

from __future__ import annotations

import json
import re
from collections.abc import Iterator, Sequence
from pathlib import Path

from beartype import beartype

from ..domain.types import Correction, SessionDigest


def _as_str(value: object) -> str:
    return value if isinstance(value, str) else ""


# Generic harness-injected text that is NEVER a user's intent — filtered for
# every user. (User-specific noise, e.g. an automation's prompt, is configured
# separately via the harvester's ignore_patterns.)
_NOISE_PREFIXES = (
    "<system-reminder>",
    "<command-",
    "<local-command-",
    "<bash-",
)
_NOISE_SUBSTRINGS = (
    "This session is being continued from a previous conversation",
    "Caveat: The messages below were generated by the user",
    "Continue from where you left off",
)

# A correction is the user redirecting the agent — detected at the START of the
# message (corrections lead with the redirect), after an assistant turn.
_CORRECTION_SIGNALS = re.compile(
    r"\b("
    r"no|nope|not that|that'?s not|thats not|that'?s wrong|wrong|incorrect|"
    r"instead|actually|i (?:already )?said|i meant|stop|undo|revert|don'?t|do not"
    r")\b",
    re.I,
)


def _is_harness_noise(text: str) -> bool:
    stripped = text.lstrip()
    if any(stripped.startswith(prefix) for prefix in _NOISE_PREFIXES):
        return True
    return any(marker in text for marker in _NOISE_SUBSTRINGS)


def _is_correction(text: str) -> bool:
    return bool(_CORRECTION_SIGNALS.search(text[:120]))


def _first_user_text(content: object) -> str:
    """Extract the user's task text from either string or list-of-blocks content.

    Handling both shapes is the landmine the reference extractor tripped on:
    list-format user text was silently dropped, losing the exact intent signal.
    """
    if isinstance(content, str):
        text = content.strip()
    elif isinstance(content, list):
        parts: list[str] = []
        for block in content:
            if isinstance(block, dict) and block.get("type") == "text":
                piece = block.get("text")
                if isinstance(piece, str):
                    parts.append(piece)
        text = " ".join(parts).strip()
    else:
        return ""
    if _is_harness_noise(text):
        return ""
    return text[:200]


class JsonlTranscriptHarvester:
    """Harvests finished Claude Code transcripts into ``SessionDigest`` summaries."""

    def __init__(
        self,
        projects_dir: Path | None = None,
        ignore_patterns: Sequence[str] = (),
    ) -> None:
        self._root = projects_dir or (Path.home() / ".claude" / "projects")
        # User-configured noise (e.g. an automation's prompt). Case-insensitive
        # substring match — generic harness noise is handled above, for everyone.
        self._ignore = tuple(p.lower() for p in ignore_patterns if p.strip())

    def _is_ignored(self, text: str) -> bool:
        low = text.lower()
        return any(pattern in low for pattern in self._ignore)

    @beartype
    def harvest(self, since: float | None = None) -> Sequence[SessionDigest]:
        digests: list[SessionDigest] = []
        if not self._root.is_dir():
            return digests
        for transcript in sorted(self._root.glob("*/*.jsonl")):
            try:
                if since is not None and transcript.stat().st_mtime < since:
                    continue
            except OSError:
                continue
            digest = self._digest(transcript)
            if digest is not None:
                digests.append(digest)
        return digests

    def _digest(self, transcript: Path) -> SessionDigest | None:
        session_id = ""
        cwd = ""
        intent = ""
        tool_calls = 0
        saw_record = False
        prev_role = ""
        last_request = ""
        corrections: list[Correction] = []
        for rec in self._stream(transcript):
            saw_record = True
            if not session_id:
                session_id = _as_str(rec.get("sessionId"))
            if not cwd:
                cwd = _as_str(rec.get("cwd"))
            msg = rec.get("message")
            if not isinstance(msg, dict):
                continue
            content = msg.get("content")
            role = msg.get("role")
            if role == "user":
                text = _first_user_text(content)
                if text and not self._is_ignored(text):
                    if prev_role == "assistant" and _is_correction(text):
                        corrections.append(Correction(last_request or intent, text))
                    else:
                        last_request = text
                        if not intent:
                            intent = text
            if isinstance(content, list):
                for block in content:
                    if isinstance(block, dict) and block.get("type") == "tool_use":
                        tool_calls += 1
            if role in ("user", "assistant"):
                prev_role = role
        if not saw_record:
            return None
        if not session_id:
            session_id = transcript.stem
        project = Path(cwd).name if cwd else transcript.parent.name
        return SessionDigest(
            session_id, project, cwd, intent, tool_calls, str(transcript), tuple(corrections)
        )

    @staticmethod
    def _stream(transcript: Path) -> Iterator[dict[str, object]]:
        try:
            with transcript.open(encoding="utf-8", errors="replace") as fh:
                for raw in fh:
                    line = raw.strip()
                    if not line:
                        continue
                    try:
                        rec = json.loads(line)
                    except json.JSONDecodeError:
                        continue
                    if isinstance(rec, dict):
                        yield rec
        except OSError:
            return
